apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesJson6902:
- path: bgd-deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: bgd
    version: v1
resources:
- ../../base
